# Pandas

Principais estruturas

- Series - um vetor
- Dataframes - matriz bidimensional com colunas rotuladas e linhas indexadas

### Importar o pacote pandas

In [1]:
import pandas as pd

### Criar uma Série

In [2]:
# Série a partir de uma lista

datas_das_aulas = pd.Series([
    "20260319",
    "20260320",
    "20260323",
    "20260324",
    "20260325",
    "20260326",
    "20260330",
    "20260331",
    "20260401",
])

datas_das_aulas

0    20260319
1    20260320
2    20260323
3    20260324
4    20260325
5    20260326
6    20260330
7    20260331
8    20260401
dtype: str

In [3]:
# Série a partir de uma tupla

sequencia = pd.Series((0,3,6,9,12))
sequencia

0     0
1     3
2     6
3     9
4    12
dtype: int64

In [4]:
# Série a partir de um dicionário

serie_notas = pd.Series(
    {
        "fulano": 7.5,
        "beltrano": 6.5,
        "ciclano": 5.0
    }
)
serie_notas

# note como as chaves viraram índices das linhas

fulano      7.5
beltrano    6.5
ciclano     5.0
dtype: float64

In [5]:
# Séria a partir de lista de valores e lista de índicies

serie_notas_versao2 = pd.Series(
    [7.5, 6.5, 5.0],
    index = ["fulano", "beltrano", "ciclano"]
    
)

serie_notas_versao2

fulano      7.5
beltrano    6.5
ciclano     5.0
dtype: float64

### Carregar arquivo CSV em um dataframe

In [6]:
dataframe = pd.read_csv("dados/dia-mes-temp.csv")

In [7]:
dataframe

    Dia do Mês  Temperatura °C
0            1            15.5
1            3            14.0
2            5            13.5
3            7            18.0
4            9            19.5
5           11            20.0
6           13            13.5
7           15            13.5
8           17            18.0
9           19            20.0
10          21            18.5
11          23            13.5
12          25            21.5
13          27            20.0
14          29            16.0

### Exibir cabeçalho e rodapé - head() e tail()

In [8]:
dataframe.head()

   Dia do Mês  Temperatura °C
0           1            15.5
1           3            14.0
2           5            13.5
3           7            18.0
4           9            19.5

In [9]:
dataframe.tail()

    Dia do Mês  Temperatura °C
10          21            18.5
11          23            13.5
12          25            21.5
13          27            20.0
14          29            16.0

In [10]:
# determinando o comprimento do cabeçalho
dataframe.head(6)

   Dia do Mês  Temperatura °C
0           1            15.5
1           3            14.0
2           5            13.5
3           7            18.0
4           9            19.5
5          11            20.0

In [11]:
# determinando o comprimento do rodapé
dataframe.tail(6)

    Dia do Mês  Temperatura °C
9           19            20.0
10          21            18.5
11          23            13.5
12          25            21.5
13          27            20.0
14          29            16.0

### Determinar quantidade de entradas do dataframe - comprimento

In [12]:
len(dataframe)

15

### Examinar tipos de dados - dtypes

In [13]:
# note que dtypes é uma propriedade e não uma função
dataframe.dtypes

Dia do Mês          int64
Temperatura °C    float64
dtype: object

### Estatísticas básicas - describe()

Esta função lista, para cada coluna do dataframe, as estatísticas básicas:

- contagem de observações (linhas)
- média (mean)
- desvio padrão (std)
- mínimo (min)
- quartis (1Q = 25%, 2Q = 50%, 3Q = 75%)
- máximo (max)

In [14]:
dataframe.describe()

       Dia do Mês  Temperatura °C
count   15.000000       15.000000
mean    15.000000       17.000000
std      8.944272        2.915476
min      1.000000       13.500000
25%      8.000000       13.750000
50%     15.000000       18.000000
75%     22.000000       19.750000
max     29.000000       21.500000

### Acessando colunas

Pelo nome:

In [ ]:
dataframe['Dia do Mês'] # resultado é uma série

0      1
1      3
2      5
3      7
4      9
5     11
6     13
7     15
8     17
9     19
10    21
11    23
12    25
13    27
14    29
Name: Dia do Mês, dtype: int64

In [ ]:
dataframe[["Dia do Mês"]] # resultado é um dataframe - note os colchetes duplos

    Dia do Mês
0            1
1            3
2            5
3            7
4            9
5           11
6           13
7           15
8           17
9           19
10          21
11          23
12          25
13          27
14          29

### Acessando linhas

#### Pelo índice - iloc

note que `iloc` é uma propriedade.

In [ ]:
dataframe.iloc[3] #

Dia do Mês         7.0
Temperatura °C    18.0
Name: 3, dtype: float64

#### Pelo rótulo (label) da linha - loc

Se as linhas do dataframe receberam rótulos, podemos pesquisar usando ele (pela label)

In [17]:
dados = pd.DataFrame(
    data = [7.5, 6.5, 5.0],
    columns= ["Nota"],
    index =["Fulano", "Beltrano", "Ciclano"]
)
dados

          Nota
Fulano     7.5
Beltrano   6.5
Ciclano    5.0

In [18]:
# Pesquisa por label usando loc
dados.loc["Beltrano"]

Nota    6.5
Name: Beltrano, dtype: float64

### Dataframe com rótulos de linha e várias colunas

Neste exemplo, o dataframe contém:
- 6 linhas

e cada linha do dataframe contém:

- índice - uma data
- 4 observações de valores aleatórios com uma distribuição normal

In [19]:
import pandas as pd
import numpy as np

datas = pd.date_range("20260301", periods=6) # serão os índices
datas

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05', '2026-03-06'],
              dtype='datetime64[us]', freq='D')

In [20]:
np.random.randn(6,4) # valores para preencher o dataframe

array([[-0.45994004, -0.25432962,  0.64276574,  0.51263092],
       [-0.24960686,  0.31009023, -1.60317603, -1.06908128],
       [-2.32481034,  0.17064423,  0.10267567,  0.62008918],
       [ 0.40052912, -0.07206321,  0.87047867, -1.07084355],
       [-1.33295201,  2.99030256,  1.94582388,  1.08643158],
       [-0.90613139,  0.41812612,  0.70944862,  0.88843574]])

In [21]:
colunas = list("ABCD") # nomes das colunas
colunas

['A', 'B', 'C', 'D']

In [22]:

df = pd.DataFrame(
    data = np.random.randn(6,4),
    index = datas,
    columns = colunas
    )
df

                   A         B         C         D
2026-03-01  1.763928  0.019769  0.253228  1.480030
2026-03-02 -1.488046  0.296941 -1.813197 -0.161490
2026-03-03 -1.271406  0.526160 -0.178519  1.335032
2026-03-04  1.500819 -0.999401  1.154317 -0.433140
2026-03-05 -0.619531 -0.755242 -0.513536 -0.226153
2026-03-06  1.583742 -0.633488  0.441136  0.182396

### Pesquisa por intervalo - [início: fim]

In [23]:
dataframe[:7] # do início ao ítem 7 (exclusive) - sete primeiros ítens

   Dia do Mês  Temperatura °C
0           1            15.5
1           3            14.0
2           5            13.5
3           7            18.0
4           9            19.5
5          11            20.0
6          13            13.5

In [24]:
dataframe[-7:] # do ítem 7 (inclusive) até o final

    Dia do Mês  Temperatura °C
8           17            18.0
9           19            20.0
10          21            18.5
11          23            13.5
12          25            21.5
13          27            20.0
14          29            16.0

In [25]:
dataframe[3:10] # do ítem 3 (quarta linha) até o ítem 10 (exclusive)

   Dia do Mês  Temperatura °C
3           7            18.0
4           9            19.5
5          11            20.0
6          13            13.5
7          15            13.5
8          17            18.0
9          19            20.0

In [26]:
dataframe[-5:] # os últimos 5 ítens - início = contando 5 de trás pra frente; fim: último ítem

    Dia do Mês  Temperatura °C
10          21            18.5
11          23            13.5
12          25            21.5
13          27            20.0
14          29            16.0

In [27]:
dataframe[:-5] # todos os ítens exceto os 5 últimos

   Dia do Mês  Temperatura °C
0           1            15.5
1           3            14.0
2           5            13.5
3           7            18.0
4           9            19.5
5          11            20.0
6          13            13.5
7          15            13.5
8          17            18.0
9          19            20.0

### Selecionando colunas por intervalo - iloc[linhas, colunas]

Este formato de pesquisa retorna um dataframe.

In [28]:
dataframe.iloc[0:, 0:1] # retorna a primeira coluna

    Dia do Mês
0            1
1            3
2            5
3            7
4            9
5           11
6           13
7           15
8           17
9           19
10          21
11          23
12          25
13          27
14          29

In [29]:
dataframe.iloc[0:5, 0:1] # retorna as 5 primeiras linhas da primeira coluna

   Dia do Mês
0           1
1           3
2           5
3           7
4           9

In [30]:
dataframe.iloc[0:5, 1:2] # retorna as 5 primeiras linhas da segunda coluna

   Temperatura °C
0            15.5
1            14.0
2            13.5
3            18.0
4            19.5

Este formato retorna uma série.

Note que aqui estamos passando apenas o índice da coluna e não um intervalo do tipo [início:fim]

In [31]:
dataframe.iloc[0:5, 1] # retorna a primeira coluna

0    15.5
1    14.0
2    13.5
3    18.0
4    19.5
Name: Temperatura °C, dtype: float64

### Acessando os valores de uma coluna ou série em formato `numpy` - array

In [32]:
dataframe.iloc[0:5, 1].values

array([15.5, 14. , 13.5, 18. , 19.5])

### Carregar CSV com nomes de índice para as linhas

In [33]:
df_aulas = pd.read_csv("dados/aulas.csv", index_col=0)
df_aulas

                                                    assunto
data
20260319                      Variáveis em python - revisão
20260320         aula 1 - A natureza abstrata da matemática
20260323         aula 2 - Exercícios: Pensamento Matemático
20260324  aula 3 - Ambiguidade, álgebra, R (uso, sintaxe...
20260325  aula 4 - Medidas de tendência central e variab...
20260326  aula 5 - Medidas de tendência central e variab...
20260330  aula 6 - Apuração de dados - data frames, tabe...
20260331  aula 7 - Variância e desvio padrão, distribuiç...
20260401  aula 8 - Funções lineares e introdução à regre...

Pesquisando pelo índice

In [34]:
df_aulas.loc[20260331]

assunto    aula 7 - Variância e desvio padrão, distribuiç...
Name: 20260331, dtype: str

### Salvar um dataframe em disco

In [35]:
df_aulas.to_csv("df_aulas.csv")

#### sem o cabeçalho

In [36]:
df_aulas.to_csv("df_aulas_sem_cab.csv", header=False)